# Define the root directory for artifacts
artifact_root: artifacts

# Configuration for data ingestion
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1Cbowka-nMgOAQIL_N3NVWBpo4eioCf8O/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.7z
  unzip_dir: artifacts/data_ingestion


